name: Build & Deploy Pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 15 * * *"   # daily 15:00 UTC ≈ 08:00 PT (PDT)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: python -m src.build

      # === Inject GA4 after build, before upload ===
      - name: Inject GA4 snippet into HTML
        env:
          GA_MEASUREMENT_ID: "G-68SNW6M6T4"
        run: |
          set -e

          # 1) Build snippet via heredoc
          SNIPPET="<!-- GA4 start -->
          <script async src=\"https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}\"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          </script>
          <!-- GA4 end -->"
          # 仅对还未注入过的 HTML 文件处理；把片段插到 </head> 之前
          while IFS= read -r -d '' file; do
            if ! grep -q "<!-- GA4 start -->" "$file"; then
              awk -v snippet="$SNIPPET" '
                BEGIN{IGNORECASE=1}
                /<\/head>/ { sub(/<\/head>/, snippet "\n</head>") }
                { print }
              ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            fi
          done < <(find public -type f -name "*.html" -print0)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
